server:
  port: 8050
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  config:
    import: "optional:configserver:"
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/: